### ISSUE TITLE
Update apa.csl

### ISSUE THREAD

**Issue by darrenleeweber** [inukshuk/citeproc-ruby#38]
The fixture data for `apa.csl` was last updated 4 years ago.  Is it time to pull in an update from
https://github.com/citation-style-language/styles/blob/master/apa.csl

**Comment by inukshuk** [comment]
This is just a fixture we use to test an arbitrary but realistic style. The style itself is of little consequence here. You can install more recent styles using the 'csl-styles' gem or you can just download the styles you need (just point `CSL::Style.root` to the directory and you can load any style with just its name using `CSL::Style.load`).
