### ISSUE TITLE
Title casing results in invalid HTML escape sequences

### ISSUE THREAD

**Issue by RubenVerborgh** [inukshuk/citeproc-ruby#44]
When trying the following code with citeproc-ruby 1.1.5:

```ruby
require 'citeproc'
require 'csl/styles'

cp = CiteProc::Processor.new format: 'html'
cp << CiteProc::CitationItem.new(
  :id => 'test',
  :author => 'First Last',
  :'container-title' => 'one & two & three',
)
puts cp.render(:bibliography, id: 'test').first
```

the output is

```html
Last, First. n.d. <i>One &Amp; Two &Amp; Three</i>.
```

whereas it should be

```html
Last, First. n.d. <i>One &amp; Two &amp; Three</i>.
```

Note how the `&amp;` escape sequence incorrectly was capitalized; i.e., it seems that capitalization is applied after HTML instead of before, while it should be the other way round.

**Comment by inukshuk** [comment]
Good catch, thanks!

**Comment by RubenVerborgh** [comment]
And impressive one-word fix, thanks!
