### ISSUE TITLE
Superscripts produce invalid CSS

### ISSUE THREAD

**Issue by fallax** [inukshuk/citeproc-ruby#45]
Numeric CSL styles which format the citation number with superscript seem to contain something like this:

```
<citation collapse="citation-number">
    <sort>
      <key variable="citation-number"/>
    </sort>
    <layout delimiter="," vertical-align="sup">
      <text variable="citation-number"/>
    </layout>
  </citation>
```

citeproc-ruby outputs the "sup" part directly into the HTML - but "vertical-align: sup" is invalid CSS (it should be "vertical-align: super" instead). As a result, the rendered HTML displays without any superscript formatting. 

The [CSL spec](http://docs.citationstyles.org/en/stable/specification.html) seems to suggest that "vertical-align: sup" is the correct CSL (even if it is wrong in CSS). 

Perhaps citeproc-ruby should be detecting this and outputting "vertical-align: super" instead?

There is currently also [a test](https://github.com/inukshuk/citeproc-ruby/blob/d8c89d615c93242fdedff39a198d0ecf57913875/spec/citeproc/ruby/formats/html_spec.rb) checking this behaviour.

**Comment by inukshuk** [comment]
You're absolutely right, thanks!

Fixed in 1.1.7
