### ISSUE TITLE
support for bluebook-law-review

### ISSUE THREAD

**Issue by mapreal19** [inukshuk/citeproc-ruby#62]
When using that style I get this error: `no CSL node:` coming from https://github.com/inukshuk/citeproc-ruby/blob/master/lib/citeproc/ruby/renderer.rb#L38

Any hints on how to fix this?

**Comment by inukshuk** [comment]
You're probably trying to render the style's `bibliography` node, but [this style does not have one](https://github.com/citation-style-language/styles/blob/master/bluebook-law-review.csl), its only rendering node being `citation`.

**Comment by mapreal19** [comment]
hmm I see. Thanks @inukshuk!
