### ISSUE TITLE
Importing non BibTex references

### ISSUE THREAD

**Issue by lizdenhup** [inukshuk/citeproc-ruby#63]
Hello!

First, thank you for making such a wonderful library.

From reading the documentation, it looks like the CiteProc::Processor only accepts BibTex references as in input, e.g. 

```
cp = CiteProc::Processor.new style: 'apa', format: 'text'
cp.import BibTeX.open('./references.bib').to_citeproc
```

Is there support for importing references as unstructured text or as an array (or hash) of CSL-JSON objects? I have both.

Thanks.

**Comment by inukshuk** [comment]
The processor does support CSL-JSON. The `to_citeproc` in the example actually converts the BibTeX to CSL-JSON, apologies for a misleading example!

**Comment by lizdenhup** [comment]
Oh, wonderful. Thank you for clarifying -- I will go ahead and close this issue. 🙂
