### ISSUE TITLE
Get output for a footnote style?

### ISSUE THREAD

**Issue by retorquere** [inukshuk/citeproc-ruby#67]
I'm currently assembling a sample rendering using

```
result = ''
cp = CiteProc::Processor.new(style: style, format: 'html')
cp.import(items)

items.each_slice(2){|citation|
  result += cp.process(citation.map{|i| { 'id' => i['id'] } }) + "<br/>\n"
}

result += "<hr/>\n"

cp.bibliography.each{|line| result += line + "<br/>\n" }
```

but for `acta-naturae.csl` I'm getting `[,]` for the results from `cp.process`. I think this may be a footnote style -- should I get the footnote text differently? I realize this sample may be too sparse, I'll be glad to elaborate where required.

**Comment by inukshuk** [comment]
You're likely just missing [a citation-number in your `CitationItem`](https://github.com/citation-style-language/styles/blob/master/acta-naturae.csl#L107).

**Comment by retorquere** [comment]
That was it, thanks!
