### ISSUE TITLE
Render multiple citations

### ISSUE THREAD

**Issue by mapreal19** [inukshuk/citeproc-ruby#69]
Is it possible to render more than one citation at the same time? I saw there is an `items` property but not sure if implemented. I was looking for something like this:

` cp.render :citation, items: [{ id: 'knuth' }, { id: 'knuth2' }] # output: (Knuth, 1968; Knuth2, 1968)`

**Comment by inukshuk** [comment]
It's definitely implemented yes (some styles treat multi-cites very differently than, e.g., citing the same references in a row).

**Comment by inukshuk** [comment]
I'd have to check but I think you are supposed to pass a `Citeproc::CitationData` object to the render method. This can cover multiple items.

**Comment by mapreal19** [comment]
ok realized how to do it:

`cp.render :citation, [{ id: 'knuth' }, { id: 'knuth2' }] # output: (Knuth, 1968; Knuth2, 1968)

Just passing the array directly works :)
